title: TP Modeling Guide
description: Transportation Planner Modeling Guide
theme: just-the-docs

url: https://mjmanishjoshi.github.io/Sum-App-Help

aux_links:
  Repository: https://github.com/mjmanishjoshi/Sum-App-Help

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

#footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill."
    
plugins:
  - jekyll-default-layout